version: "3.9"
services:
  postgres:
    image: stop-gerry-database:latest
    ports: 
    - "54032:5432"
    environment:
      TZ: UTC
      POSTGRES_USER: Gerry
      POSTGRES_PASSWORD: YouNeedToChangeThis@123
      POSTGRES_DB: StopGerry
    volumes:
      - presistentDatabase:/var/lib/postgresql/data
    
volumes:
  presistentDatabase:
