name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      working-directory: ./StopGerry

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
    - name: Install dependencies
      working-directory: ${{env.working-directory}}
      run: dotnet restore
    - name: Build
      working-directory: ${{env.working-directory}}
      run: dotnet publish -r linux-x64 /p:PublishTrimmed=true -p:PublishSingleFile=true --self-contained true
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: StopGerry
        path: ${{env.working-directory}}/bin/Debug/net5.0/linux-x64/publish/StopGerry
