name: Publish Release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
    
jobs:
  build:
    name: Upload Release Asset

    runs-on: ubuntu-latest
    env:
      working-directory: ./StopGerry

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
    - name: Install dependencies
      working-directory: ${{env.working-directory}}
      run: dotnet restore
    - name: Publish
      id: publish
      working-directory: ${{env.working-directory}}
      run: dotnet publish -r linux-x64 /p:PublishTrimmed=true -p:PublishSingleFile=true --self-contained true
    - name: Create Release
      id: create_release
      uses: ncipollo/release-action@v1
      with:
        artifact: ${{env.working-directory}}/bin/Debug/net5.0/linux-x64/publish/StopGerry
        bodyFile: "body.md"
        token: ${{ secrets.GITHUB_TOKEN }}
      
      
